# Agricultural land area vs vegetation and phytogeographic zones
# Analysis population: declared agriculture practitioners
# Inputs: data7.xlsx and zones.xlsx
# Output: agricultural_area_zone_comparison_results.xlsx

packages<-c("readxl","dplyr","tidyr","stringr","stringi","openxlsx")
missing<-packages[!vapply(packages,requireNamespace,logical(1),quietly=TRUE)]
if(length(missing))stop("Install packages first: install.packages(c(",paste(sprintf('"%s"',missing),collapse=", "),"))")
suppressPackageStartupMessages({library(readxl);library(dplyr);library(tidyr);library(stringr);library(stringi);library(openxlsx)})
DATA_FILE<-"data7.xlsx";ZONES_FILE<-"zones.xlsx";OUTPUT_FILE<-"agricultural_area_zone_comparison_results.xlsx"
ALPHA<-0.05;B<-100000L;SEED<-20260827L
AREA_COL<-"I.- IDENTIFICATION DU CHEF DE MENAGE /Si pratique de l'agriculture, quelle est la superficie de terre agricole mise en valeur pour les cultures dans votre champ ? kanti ou ha"
MAIN_ACTIVITY_COL<-"I.- IDENTIFICATION DU CHEF DE MENAGE /Quelle est votre principale activité? : 1=Agriculture, 2=Artisanat, 3=Autre, 4=Commerce, 5=Elevage"
SECONDARY_AGRI_COL<-"I.- IDENTIFICATION DU CHEF DE MENAGE /Quelles sont vos activites secondaires ?/Agriculture: 0=Non, 1=Oui"
COMMUNE_COL<-"II- CARACTERISTIQUES DE L’UNITE D’ELEVAGE (UE) /Commune"
set.seed(SEED)
normalize_key<-function(x){x<-str_replace_all(as.character(x),"\\u00A0"," ");x<-stri_trans_general(x,"Latin-ASCII")|>str_to_lower()|>str_squish();x<-str_replace_all(x,"[’'`-]","")|>str_replace_all("[^a-z0-9]","");recode(x,"toribossito"="tori","dassazoume"="dassa","dassazounme"="dassa",.default=x)}
brown_forsythe<-function(y,g){g<-droplevels(factor(g));m<-ave(y,g,FUN=median);a<-anova(lm(abs(y-m)~g));list(F=unname(a$`F value`[1]),df1=unname(a$Df[1]),df2=unname(a$Df[2]),p=unname(a$`Pr(>F)`[1]))}
permutation_kw<-function(y,g,B){g<-droplevels(factor(g));observed<-unname(kruskal.test(y,g)$statistic);perm<-replicate(B,unname(kruskal.test(y,sample(g,replace=FALSE))$statistic));extreme<-sum(perm>=observed);p<-(extreme+1)/(B+1);se<-sqrt(p*(1-p)/(B+1));ci<-pmax(0,pmin(1,p+c(-1,1)*1.96*se));list(statistic=observed,p=p,B=B,extreme=extreme,se=se,low=ci[1],high=ci[2])}
raw<-read_excel(DATA_FILE,1,col_types="text",.name_repair="minimal");zraw<-read_excel(ZONES_FILE,1,col_types="text",.name_repair="unique")
needed<-c(AREA_COL,MAIN_ACTIVITY_COL,SECONDARY_AGRI_COL,COMMUNE_COL);missing_cols<-setdiff(needed,names(raw));if(length(missing_cols))stop("Columns not found: ",paste(missing_cols,collapse=" | "))
zones<-zraw|>transmute(vegetation_zone=str_squish(str_replace_all(`Vegetation zones`,"\\u00A0"," ")),phytogeo_zone=str_squish(str_replace_all(`Phytogeographic zones`,"\\u00A0"," ")),district=str_squish(str_replace_all(District,"\\u00A0"," ")))|>fill(vegetation_zone,phytogeo_zone)|>filter(!is.na(district),district!="",!str_detect(str_to_lower(vegetation_zone),"^total"))|>mutate(commune_key=normalize_key(district))|>select(commune_key,district,vegetation_zone,phytogeo_zone)
data<-raw|>transmute(row_id=row_number(),area_text=str_squish(.data[[AREA_COL]]),area=suppressWarnings(as.numeric(str_replace_all(area_text,",","."))),main_activity=str_squish(.data[[MAIN_ACTIVITY_COL]]),secondary_agriculture=str_squish(.data[[SECONDARY_AGRI_COL]]),commune_original=str_squish(.data[[COMMUNE_COL]]),commune_key=normalize_key(.data[[COMMUNE_COL]]))|>left_join(zones,by="commune_key")|>mutate(declared_agriculture=main_activity=="1"|secondary_agriculture=="1",inconsistent_positive=!declared_agriculture&!is.na(area)&area>0,review_flag=!is.na(area)&(area<0|area>100))
analysis<-data|>filter(declared_agriculture,!is.na(area),area>0,!is.na(vegetation_zone))

analyse<-function(df,zone_var,label){
 d<-df|>transmute(value=area,group=factor(.data[[zone_var]]))|>droplevels();if(nlevels(d$group)<2)stop(label,": at least two groups required")
 desc<-d|>group_by(group)|>summarise(N=n(),Mean=mean(value),SD=sd(value),Median=median(value),Q1=quantile(value,.25),Q3=quantile(value,.75),IQR=IQR(value),Minimum=min(value),Maximum=max(value),.groups="drop")|>rename(Group=group)
 normal<-d|>group_by(group)|>summarise(N=n(),Shapiro_W=if(n()>=3)unname(shapiro.test(value)$statistic)else NA_real_,Shapiro_p=if(n()>=3)shapiro.test(value)$p.value else NA_real_,Normality=ifelse(is.na(Shapiro_p),"Not assessed",ifelse(Shapiro_p>=ALPHA,"PASS","FAIL")),.groups="drop")|>rename(Group=group)
 bf<-brown_forsythe(d$value,d$group);kw<-kruskal.test(value~group,data=d);welch<-oneway.test(value~group,data=d,var.equal=FALSE);set.seed(SEED+ifelse(zone_var=="phytogeo_zone",100,0));mc<-permutation_kw(d$value,d$group,B)
 eps<-max(0,(unname(kw$statistic)-nlevels(d$group)+1)/(nrow(d)-nlevels(d$group)))
 summary<-data.frame(Comparison=label,Analysis_population="Declared agriculture practitioners with positive area",Valid_N=nrow(d),Groups=nlevels(d$group),Alpha=ALPHA,Primary_test="Kruskal-Wallis rank-sum test",Primary_statistic=unname(kw$statistic),Primary_df=unname(kw$parameter),Primary_p_value=kw$p.value,Primary_decision=ifelse(kw$p.value<ALPHA,"Statistically significant difference","No statistically significant difference"),Effect_size_epsilon_squared=eps,Brown_Forsythe_F=bf$F,Brown_Forsythe_df1=bf$df1,Brown_Forsythe_df2=bf$df2,Brown_Forsythe_p=bf$p,Welch_test=ifelse(nlevels(d$group)==2,"Welch two-sample t-test","Welch one-way ANOVA"),Welch_statistic=unname(welch$statistic),Welch_df1=unname(welch$parameter[1]),Welch_df2=if(length(welch$parameter)>1)unname(welch$parameter[2])else NA_real_,Welch_p_value=welch$p.value,Monte_Carlo_method="Permutation Kruskal-Wallis test",Monte_Carlo_statistic=mc$statistic,Monte_Carlo_B=mc$B,Monte_Carlo_extreme_count=mc$extreme,Monte_Carlo_p=mc$p,Monte_Carlo_SE=mc$se,Monte_Carlo_95CI_low=mc$low,Monte_Carlo_95CI_high=mc$high,Recommendation="Report Kruskal-Wallis as primary because area is strongly skewed; report Monte Carlo and Welch as sensitivity analyses.",stringsAsFactors=FALSE)
 list(summary=summary,desc=desc,normal=normal)
}
veg<-analyse(analysis,"vegetation_zone","Agricultural area vs vegetation zone");phyto<-analyse(analysis,"phytogeo_zone","Agricultural area vs phytogeographic zone");summary<-bind_rows(veg$summary,phyto$summary)
quality<-data.frame(Parameter=c("Rows read","Declared agriculture practitioners","Analyzed positive areas","Declared practitioners with zero area","Missing/non-numeric area","Positive area without declared agriculture","Unmatched analyzed records","Values flagged <0 or >100","Minimum analyzed area","Maximum analyzed area"),Value=c(nrow(data),sum(data$declared_agriculture),nrow(analysis),sum(data$declared_agriculture&!is.na(data$area)&data$area==0),sum(is.na(data$area)),sum(data$inconsistent_positive),sum(data$declared_agriculture&is.na(data$vegetation_zone)),sum(data$review_flag),min(analysis$area),max(analysis$area)))
inconsistent<-data|>filter(inconsistent_positive)|>select(row_id,area_text,area,main_activity,secondary_agriculture,commune_original)
notes<-data.frame(Topic=c("Outcome type","Analysis population","Zero values","Unit warning","Primary test","Monte Carlo role","Welch role","Independence","Survey design"),Assessment=c("Cultivated agricultural area is quantitative.","A respondent is treated as an agriculture practitioner if main activity is Agriculture or secondary Agriculture is Yes.","Zeros are excluded as not-applicable because all declared practitioners have positive values.","The header says kanti or ha. Values must be converted to one common unit before inferential testing if both units were actually recorded. The current script assumes all numeric values are already comparable.","Kruskal-Wallis is primary because area is strongly right-skewed.","A permutation Kruskal-Wallis test with 100,000 permutations is included as a sensitivity analysis.","Welch tests compare means without equal-variance assumptions and are included as sensitivity analyses.","Each farmer must provide one independent observation.","If weights, strata, or village clusters apply, use survey-adjusted or multilevel methods."))
wb<-createWorkbook();hdr<-createStyle(fontColour="white",fgFill="#1F4E78",textDecoration="bold",halign="center",wrapText=TRUE)
write_sheet<-function(n,x){addWorksheet(wb,n,gridLines=FALSE);writeData(wb,n,x,headerStyle=hdr,withFilter=TRUE);freezePane(wb,n,firstRow=TRUE);setColWidths(wb,n,1:ncol(x),"auto")}
write_sheet("Summary",summary);write_sheet("Veg_descriptives",veg$desc);write_sheet("Veg_normality",veg$normal);write_sheet("Phyto_descriptives",phyto$desc);write_sheet("Phyto_normality",phyto$normal);write_sheet("Data_quality",quality);if(nrow(inconsistent)>0)write_sheet("Inconsistent_records",inconsistent);write_sheet("Method_notes",notes)
setColWidths(wb,"Summary",1:ncol(summary),18);setColWidths(wb,"Summary",c(1,2,6,16,21,29),c(42,48,32,28,45,100));setColWidths(wb,"Method_notes",1:2,c(32,120));numcols<-which(vapply(summary,is.numeric,logical(1)));addStyle(wb,"Summary",createStyle(numFmt="0.0000"),rows=2:3,cols=numcols,gridExpand=TRUE)
saveWorkbook(wb,OUTPUT_FILE,overwrite=TRUE);cat("Results exported to",OUTPUT_FILE,"\n");print(summary)
