# Family member leads animals to pasture (No/Yes) vs vegetation and phytogeographic zones
# Inputs: data7.xlsx and zones.xlsx
# Output: chi_square_results_family_member_pasture_zones.xlsx
packages<-c("readxl","dplyr","tidyr","stringr","stringi","openxlsx")
missing<-packages[!vapply(packages,requireNamespace,logical(1),quietly=TRUE)]
if(length(missing))stop("Install packages first: install.packages(c(",paste(sprintf('"%s"',missing),collapse=", "),"))")
suppressPackageStartupMessages({library(readxl);library(dplyr);library(tidyr);library(stringr);library(stringi);library(openxlsx)})
DATA_FILE<-"data7.xlsx";ZONES_FILE<-"zones.xlsx";OUTPUT_FILE<-"chi_square_results_family_member_pasture_zones.xlsx"
ALPHA<-0.05;B<-100000L;SEED<-20260828L
FAMILY_MEMBER_PASTURE_COL<-"4.) Conduite des animaux/Si oui, qui assure la conduite au pâturage ?/3=membre de la famille/0=Non, 1=Oui"
PARENT_PASTURE_COL<-"4.) Conduite des animaux/Vos animaux sont-ils conduits au pâturage ? 0=Non, 1=Oui"
COMMUNE_COL<-"II- CARACTERISTIQUES DE L’UNITE D’ELEVAGE (UE) /Commune"
normalize_key<-function(x){x<-str_replace_all(as.character(x),"\\u00A0"," ");x<-stri_trans_general(x,"Latin-ASCII")|>str_to_lower()|>str_squish();x<-str_replace_all(x,"[’'`-]","")|>str_replace_all("[^a-z0-9]","");recode(x,"toribossito"="tori","dassazoume"="dassa","dassazounme"="dassa",.default=x)}
raw<-read_excel(DATA_FILE,1,col_types="text",.name_repair="minimal");zraw<-read_excel(ZONES_FILE,1,col_types="text",.name_repair="unique")
if(!FAMILY_MEMBER_PASTURE_COL%in%names(raw))stop("Family-member pasture column not found exactly in data7.xlsx");if(!PARENT_PASTURE_COL%in%names(raw))stop("Parent pasture-conduct column not found exactly in data7.xlsx");if(!COMMUNE_COL%in%names(raw))stop("Commune column not found exactly")
zones<-zraw|>transmute(vegetation_zone=str_squish(str_replace_all(`Vegetation zones`,"\\u00A0"," ")),phytogeo_zone=str_squish(str_replace_all(`Phytogeographic zones`,"\\u00A0"," ")),district=str_squish(str_replace_all(District,"\\u00A0"," ")))|>fill(vegetation_zone,phytogeo_zone)|>filter(!is.na(district),district!="",!str_detect(str_to_lower(vegetation_zone),"^total"))|>mutate(commune_key=normalize_key(district))|>select(commune_key,district,vegetation_zone,phytogeo_zone)
data<-raw|>transmute(parent_pasture=str_squish(.data[[PARENT_PASTURE_COL]]),family_member_pasture_code=str_squish(.data[[FAMILY_MEMBER_PASTURE_COL]]),commune_original=str_squish(.data[[COMMUNE_COL]]),commune_key=normalize_key(.data[[COMMUNE_COL]]))|>mutate(eligible=parent_pasture=="1",family_member_pasture=factor(family_member_pasture_code,levels=c("0","1"),labels=c("No","Yes")),invalid_family_member_pasture=eligible&is.na(family_member_pasture)&!is.na(family_member_pasture_code)&family_member_pasture_code!="",ineligible_positive=parent_pasture=="0"&family_member_pasture_code=="1")|>left_join(zones,by="commune_key")
run_test<-function(df,zone_var,label){
 d<-df|>filter(eligible,!is.na(family_member_pasture),!is.na(.data[[zone_var]]))|>droplevels();obs<-table(d$family_member_pasture,d[[zone_var]]);pearson<-suppressWarnings(chisq.test(obs,correct=FALSE));exp<-pearson$expected;n<-sum(obs);cells<-length(exp);dfchi<-(nrow(obs)-1)*(ncol(obs)-1);n5<-sum(exp<5);n1<-sum(exp<1);pct5<-100*n5/cells;margins<-!any(rowSums(obs)==0)&!any(colSums(obs)==0);valid<-n1==0&pct5<=20&margins
 set.seed(SEED+ifelse(zone_var=="phytogeo_zone",100,0));mc<-chisq.test(obs,simulate.p.value=TRUE,B=B);mcse<-sqrt(mc$p.value*(1-mc$p.value)/(B+1));mcl<-max(0,mc$p.value-1.96*mcse);mch<-min(1,mc$p.value+1.96*mcse)
 if(valid){selected<-pearson;method<-"Pearson chi-square (asymptotic)"}else{selected<-mc;method<-paste0("Pearson chi-square with Monte Carlo p-value (B=",B,")")}
 v<-sqrt(unname(pearson$statistic)/(n*min(nrow(obs)-1,ncol(obs)-1)));pct<-prop.table(obs,margin=2)*100
 sm<-data.frame(Comparison=label,N=n,Rows=nrow(obs),Columns=ncol(obs),Cell_count=cells,Degrees_of_freedom=dfchi,Pearson_chi_square=unname(pearson$statistic),Asymptotic_p_value=pearson$p.value,Minimum_expected=min(exp),Cells_expected_below_5=n5,Percent_expected_below_5=pct5,Cells_expected_below_1=n1,Nonzero_margins=ifelse(margins,"PASS","FAIL"),Asymptotic_chi_square_valid=ifelse(valid,"YES","NO"),Selected_test=method,Selected_p_value=selected$p.value,Monte_Carlo_B=B,Monte_Carlo_p_value=mc$p.value,Monte_Carlo_SE=mcse,Monte_Carlo_95CI_low=mcl,Monte_Carlo_95CI_high=mch,Alpha=ALPHA,Decision=ifelse(selected$p.value<ALPHA,"Statistically significant association","No statistically significant association"),Cramers_V=v,Recommendation=ifelse(valid,"Report ordinary Pearson chi-square; Monte Carlo is supplied as sensitivity analysis.","Report Monte Carlo p-value because expected-count conditions fail."),stringsAsFactors=FALSE)
 list(summary=sm,observed=obs,expected=exp,stdres=pearson$stdres,percent=pct)
}
veg<-run_test(data,"vegetation_zone","Family member leads animals to pasture vs vegetation zone");phyto<-run_test(data,"phytogeo_zone","Family member leads animals to pasture vs phytogeographic zone");summary<-bind_rows(veg$summary,phyto$summary)
matrix_df<-function(x){z<-as.data.frame.matrix(x);data.frame(`Family member leads animals to pasture`=rownames(z),z,check.names=FALSE,row.names=NULL)}
quality<-data.frame(Parameter=c("Rows read","Eligible units whose animals go to pasture","Eligible valid family-member records","Eligible No","Eligible Yes","Eligible missing responses","Eligible invalid codes","Ineligible positive responses","Unmatched eligible zone records"),Value=c(nrow(data),sum(data$eligible),sum(data$eligible&!is.na(data$family_member_pasture)),sum(data$eligible&data$family_member_pasture=="No",na.rm=TRUE),sum(data$eligible&data$family_member_pasture=="Yes",na.rm=TRUE),sum(data$eligible&(is.na(data$family_member_pasture_code)|data$family_member_pasture_code=="")),sum(data$invalid_family_member_pasture),sum(data$ineligible_positive),sum(data$eligible&is.na(data$vegetation_zone))))
notes<-data.frame(Parameter=c("Variable type","Code 0 interpretation","Null hypothesis","Expected-count rule","Monte Carlo","Multiple-response caution","Independence","Survey design"),Assessment=c("Family member leads animals to pasture and zone are qualitative variables, so chi-square is appropriate.","The source label defines 0=No and 1=Yes.","Family member leads animals to pasture status and zone are independent.","No expected count below 1 and no more than 20% below 5.","Monte Carlo with 100,000 simulations is exported as sensitivity analysis and selected only if expected-count conditions fail.","This is a conditional modality of a multiple-response herding-person question. Analysis is restricted to livestock units whose animals are led to pasture. Analyze each responsible-person modality separately and adjust p-values if several are tested.","Among eligible livestock units, each unit contributes once to the family-member pasture table.","Use Rao-Scott chi-square if weights, strata, or village clusters apply."))
wb<-createWorkbook();hdr<-createStyle(fontColour="white",fgFill="#1F4E78",textDecoration="bold",halign="center",wrapText=TRUE)
write_sheet<-function(n,x){addWorksheet(wb,n,gridLines=FALSE);writeData(wb,n,x,headerStyle=hdr,withFilter=TRUE);freezePane(wb,n,firstRow=TRUE);setColWidths(wb,n,1:ncol(x),"auto")}
write_sheet("Summary",summary);write_sheet("Veg_observed",matrix_df(veg$observed));write_sheet("Veg_expected",matrix_df(round(veg$expected,4)));write_sheet("Veg_percent",matrix_df(round(veg$percent,2)));write_sheet("Veg_std_residuals",matrix_df(round(veg$stdres,4)));write_sheet("Phyto_observed",matrix_df(phyto$observed));write_sheet("Phyto_expected",matrix_df(round(phyto$expected,4)));write_sheet("Phyto_percent",matrix_df(round(phyto$percent,2)));write_sheet("Phyto_std_residuals",matrix_df(round(phyto$stdres,4)));write_sheet("Data_quality",quality);write_sheet("Validity_notes",notes)
setColWidths(wb,"Summary",1:ncol(summary),18);setColWidths(wb,"Summary",c(1,15,23,25),c(42,55,42,85));setColWidths(wb,"Validity_notes",1:2,c(35,110));numcols<-which(vapply(summary,is.numeric,logical(1)));addStyle(wb,"Summary",createStyle(numFmt="0.0000"),rows=2:3,cols=numcols,gridExpand=TRUE)
saveWorkbook(wb,OUTPUT_FILE,overwrite=TRUE);cat("Results exported to",OUTPUT_FILE,"\n");print(summary)
